title: Rotate your camera with your mouse
hero_image: images/banner.png
description: Rotate your camera with your mouse
version: 1
listed: false
copyedit: false
last_tested: "2023-05-22"
steps:
  - title: Rotate your camera with your mouse
